CREATE DATABASE agregator_db;
\c agregator_db;

CREATE TABLE hotels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  adress VARCHAR(100) NOT NULL,
  country_code CHAR(2) NOT NULL
);

CREATE TABLE room_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  hotel_id BIGINT NOT NULL REFERENCES hotels(id) ON DELETE CASCADE
);

CREATE TABLE conviniences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE room_type_conviniences (
  room_type_id BIGINT NOT NULL REFERENCES room_types(id) ON DELETE CASCADE,
  convinience_id BIGINT NOT NULL REFERENCES conviniences(id) ON DELETE CASCADE,
  PRIMARY KEY (room_type_id, convinience_id)
);

CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE bookings (
  id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkin_date DATE NOT NULL,
  checkout_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  room_type_id BIGINT NOT NULL REFERENCES room_types(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating SMALLINT NOT NULL,
  comment TEXT,
  booking_id BIGINT NOT NULL UNIQUE REFERENCES bookings(id) ON DELETE CASCADE
);

INSERT INTO hotels (name, adress, country_code)
VALUES
  ('Grand Riverside', '100 River Rd, Sacramento', 'US'),
  ('City Lodge Central', '21 Center St, London', 'GB');

INSERT INTO room_types (name, price, hotel_id)
VALUES
  ('Deluxe King', 150.00, 1),
  ('Twin Superior', 120.00, 1),
  ('Standard Double', 100.00, 2);

INSERT INTO conviniences (name)
VALUES
  ('Wi-Fi'),
  ('Parking'),
  ('Air Conditioning'),
  ('Television');

INSERT INTO room_type_conviniences (room_type_id, convinience_id)
VALUES
  (1, 1),
  (1, 4),
  (2, 1),
  (2, 3),
  (3, 1),
  (3, 2);

INSERT INTO clients (name, email)
VALUES
  ('Alice Smith', 'alice@example.com'),
  ('Bob Johnson', 'bob@example.co.uk');

INSERT INTO bookings (checkin_date, checkout_date, status, client_id, room_type_id)
VALUES
  ('2025-01-06', '2025-01-09', 'CONFIRMED', 1, 1),
  ('2025-02-01', '2025-02-05', 'CANCELLED', 2, 3);

INSERT INTO reviews (rating, comment, booking_id)
VALUES
  (5, 'Great stay! Clean room and friendly staff.', 1);

